# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       xorg-x11-proto-trapproto
Summary:    X.Org X11 Protocol trapproto
Version:    3.4.3
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/trapproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-trapproto.yaml
BuildRequires:  pkgconfig(xt)
Provides:   trapproto

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Description: %{summary}



%prep
%setup -q -n trapproto-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/pkgconfig/trapproto.pc
%{_includedir}/X11/extensions/xtrapdi.h
%{_includedir}/X11/extensions/xtrapproto.h
%{_includedir}/X11/extensions/xtrapemacros.h
%{_includedir}/X11/extensions/xtrapbits.h
%{_includedir}/X11/extensions/xtraplib.h
%{_includedir}/X11/extensions/xtrapddmi.h
%{_includedir}/X11/extensions/xtraplibp.h
# << files


